version: "3"

volumes:
  quiz-db:

services:
  quiz-api:
    build: .
    image: ar0660/quiz:latest
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GIN_MODE=release
      - QUIZ_DB_HOST=quiz-db
      - QUIZ_DB_PORT=3306
      - QUIZ_DB_USERNAME=root
      - QUIZ_DB_PASSWORD=password
      - QUIZ_DB_NAME=quiz
    depends_on:
      - quiz-db
    restart: always
    container_name: quiz-api

  quiz-db:
    image: mysql:8.0.29
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - quiz-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=quiz
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: quiz-db
